# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Application Bug Report
description: Found a problem with the application itself (ie. bad file path handling, UX issue)? Help us improve it.
title: "[BUG]: "
labels: [Bug]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Read First

        Please do not make support requests on GitHub. Our issue tracker is for tracking bugs and feature requests only.
        If you need help configuring the emulator please contact us on the [Xbox Emulation Hub Discord](https://discord.gg/xboxemus).

        Please make an effort to make sure your issue isn't already reported.

        ### Please Avoid Issues Pertaining to the Following:
        - We are **not** accepting bug reports for **PSX mode** at this time.
          - Our recommendation for emulating PSX is to use the SwanStation core in RetroArch.
        - We do **not** accept issues relating to **upscaling** at this time.
          - We are aware of the various problems with upscaling. The issue spans many games, and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling.
          - Please try your game at native resolution before creating an issue.
          - If your bug is the result of upscaling, please contact us on the Xbox Emulation Hub for assistance with various upscaling workarounds.
        - We do **not** accept issues relating to Widescreen/No-interlace/60FPS/DNAS patches at this time.

  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Steps to reproduce the behavior."
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: input
    id: rev
    attributes:
      label: XBSX2.0 Revision
      description: "Please ensure you are on the latest version before making an issue."
      placeholder: "Example: 2.0.1"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Xbox Console
      options:
      - Xbox Series X/S
      - Xbox One S/X
    validations:
      required: true
